#define SYS_WRITE   1
#define SYS_EXEC    2
#define SYS_DUP     3
#define SYS_OPEN    4
#define SYS_WAIT    5
#define SYS_MKNOD   6
#define SYS_EXEC2   7 
#define SYS_FORK    8
#define SYS_READ    9
#define SYS_EXIT    10
#define SYS_SBRK    11
#define SYS_FSTAT   12
#define SYS_CLOSE   13